// src/common/constants/status.constant.ts
export const CUSTOMER_STATUS = Object.freeze({
  PENDING_RATE_PREPARATION: 'PENDING_RATE_PREPARATION',
  PENDING_RATE_APPROVAL: 'PENDING_RATE_APPROVAL',
  RATE_APPROVED_PENDING_OFFER: 'RATE_APPROVED_PENDING_OFFER',
  DRAFTING_OFFER_LETTER: 'DRAFTING_OFFER_LETTER',
  OFFER_SENT_AWAITING_FEEDBACK: 'OFFER_SENT_AWAITING_FEEDBACK',
  OFFER_REJECTED_REVISE_RATE: 'OFFER_REJECTED_REVISE_RATE',
  OFFER_ACCEPTED_PENDING_AGREEMENT: 'OFFER_ACCEPTED_PENDING_AGREEMENT',
  DRAFTING_AGREEMENT: 'DRAFTING_AGREEMENT',
  AGREEMENT_SENT_AWAITING_SIGNATURE: 'AGREEMENT_SENT_AWAITING_SIGNATURE',
  AGREEMENT_SIGNED_PENDING_PROFILE: 'AGREEMENT_SIGNED_PENDING_PROFILE',
  PROVISIONAL_ACTIVE: 'PROVISIONAL_ACTIVE',
  PROVISIONAL_DOCS_PENDING: 'PROVISIONAL_DOCS_PENDING',
  PROVISIONAL_EXTENSION_REQUESTED: 'PROVISIONAL_EXTENSION_REQUESTED',
  PROVISIONAL_FINAL_REVIEW_PENDING: 'PROVISIONAL_FINAL_REVIEW_PENDING',
  PROVISIONAL_EXPIRED: 'PROVISIONAL_EXPIRED',
  INFO_UPDATE_PENDING_LM_APPROVAL: 'INFO_UPDATE_PENDING_LM_APPROVAL',
  ACTIVE_ACCOUNT: 'ACTIVE_ACCOUNT',
} as const);

export type CustomerStatusKey = keyof typeof CUSTOMER_STATUS;

// Allowed transitions: fromStatus -> [toStatus...]. Enforced centrally so no
// service ever does a raw `status = x` write.
export const CUSTOMER_STATUS_TRANSITIONS: Record<string, string[]> = {
  [CUSTOMER_STATUS.PENDING_RATE_PREPARATION]: [CUSTOMER_STATUS.PENDING_RATE_APPROVAL],
  [CUSTOMER_STATUS.PENDING_RATE_APPROVAL]: [
    CUSTOMER_STATUS.PROVISIONAL_ACTIVE,
    CUSTOMER_STATUS.PENDING_RATE_PREPARATION,
  ],
  [CUSTOMER_STATUS.RATE_APPROVED_PENDING_OFFER]: [],
  [CUSTOMER_STATUS.DRAFTING_OFFER_LETTER]: [CUSTOMER_STATUS.OFFER_SENT_AWAITING_FEEDBACK],
  [CUSTOMER_STATUS.OFFER_SENT_AWAITING_FEEDBACK]: [
    CUSTOMER_STATUS.PROVISIONAL_ACTIVE,
    CUSTOMER_STATUS.OFFER_REJECTED_REVISE_RATE,
  ],
  [CUSTOMER_STATUS.OFFER_REJECTED_REVISE_RATE]: [CUSTOMER_STATUS.PENDING_RATE_APPROVAL],
  [CUSTOMER_STATUS.OFFER_ACCEPTED_PENDING_AGREEMENT]: [CUSTOMER_STATUS.DRAFTING_AGREEMENT],
  [CUSTOMER_STATUS.DRAFTING_AGREEMENT]: [CUSTOMER_STATUS.AGREEMENT_SENT_AWAITING_SIGNATURE],
  [CUSTOMER_STATUS.AGREEMENT_SENT_AWAITING_SIGNATURE]: [CUSTOMER_STATUS.AGREEMENT_SIGNED_PENDING_PROFILE],
  [CUSTOMER_STATUS.AGREEMENT_SIGNED_PENDING_PROFILE]: [
    CUSTOMER_STATUS.PROVISIONAL_ACTIVE,
    CUSTOMER_STATUS.ACTIVE_ACCOUNT,
  ],
  [CUSTOMER_STATUS.PROVISIONAL_ACTIVE]: [
    CUSTOMER_STATUS.OFFER_SENT_AWAITING_FEEDBACK,
    CUSTOMER_STATUS.PROVISIONAL_EXTENSION_REQUESTED,
    CUSTOMER_STATUS.PROVISIONAL_FINAL_REVIEW_PENDING,
    CUSTOMER_STATUS.PROVISIONAL_EXPIRED,
    CUSTOMER_STATUS.ACTIVE_ACCOUNT,
  ],
  [CUSTOMER_STATUS.PROVISIONAL_EXTENSION_REQUESTED]: [
    CUSTOMER_STATUS.PROVISIONAL_ACTIVE,
    CUSTOMER_STATUS.PROVISIONAL_EXPIRED,
  ],
  [CUSTOMER_STATUS.PROVISIONAL_FINAL_REVIEW_PENDING]: [
    CUSTOMER_STATUS.ACTIVE_ACCOUNT,
    CUSTOMER_STATUS.PROVISIONAL_ACTIVE,
  ],
  [CUSTOMER_STATUS.PROVISIONAL_EXPIRED]: [],
  [CUSTOMER_STATUS.ACTIVE_ACCOUNT]: [CUSTOMER_STATUS.INFO_UPDATE_PENDING_LM_APPROVAL],
  [CUSTOMER_STATUS.INFO_UPDATE_PENDING_LM_APPROVAL]: [CUSTOMER_STATUS.ACTIVE_ACCOUNT],
};