
import { ROLES } from './roles';

export const PERMISSIONS = Object.freeze({
  CREATE_RECOMMENDATION: 'CREATE_RECOMMENDATION',
  REVISE_RECOMMENDATION: 'REVISE_RECOMMENDATION',
  REQUEST_INFO_UPDATE: 'REQUEST_INFO_UPDATE',
  APPROVE_INFO_UPDATE: 'APPROVE_INFO_UPDATE',
  APPROVE_RATE: 'APPROVE_RATE',
  REJECT_RATE: 'REJECT_RATE',
  PROCESS_APPROVED_RATE: 'PROCESS_APPROVED_RATE', // SC forwards LM-approved rate to KAM
  DRAFT_OFFER: 'DRAFT_OFFER',
  FINALIZE_OFFER: 'FINALIZE_OFFER',
  DRAFT_AGREEMENT: 'DRAFT_AGREEMENT',
  FINALIZE_AGREEMENT: 'FINALIZE_AGREEMENT',
  UPLOAD_SIGNED_AGREEMENT: 'UPLOAD_SIGNED_AGREEMENT',
  ACTIVATE_PROFILE: 'ACTIVATE_PROFILE',
  VIEW_CUSTOMER_PROFILE: 'VIEW_CUSTOMER_PROFILE',
  SUBMIT_WEEKLY_PLAN: 'SUBMIT_WEEKLY_PLAN',
  REVIEW_WEEKLY_PLAN: 'REVIEW_WEEKLY_PLAN',
  SUBMIT_DAILY_REPORT: 'SUBMIT_DAILY_REPORT',
  VIEW_FOLLOWUP_REMINDERS: 'VIEW_FOLLOWUP_REMINDERS',
  VIEW_ALL_KAM_DASHBOARDS: 'VIEW_ALL_KAM_DASHBOARDS',
  MANAGE_USERS: 'MANAGE_USERS',
  FULL_SYSTEM_CONTROL: 'FULL_SYSTEM_CONTROL',
});

const P = PERMISSIONS;

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.KAM]: [
    P.CREATE_RECOMMENDATION,
    P.REVISE_RECOMMENDATION,
    P.REQUEST_INFO_UPDATE,
    P.UPLOAD_SIGNED_AGREEMENT,
    P.ACTIVATE_PROFILE,
    P.VIEW_CUSTOMER_PROFILE,
    P.SUBMIT_WEEKLY_PLAN,
    P.SUBMIT_DAILY_REPORT,
  ],
  [ROLES.SALES_COORDINATOR]: [
    P.PROCESS_APPROVED_RATE,
    P.DRAFT_OFFER,
    P.FINALIZE_OFFER,
    P.DRAFT_AGREEMENT,
    P.FINALIZE_AGREEMENT,
    P.VIEW_CUSTOMER_PROFILE,
    P.VIEW_ALL_KAM_DASHBOARDS,
  ],
  [ROLES.LINE_MANAGER]: [
    P.APPROVE_RATE,
    P.REJECT_RATE,
    P.APPROVE_INFO_UPDATE,
    P.REVIEW_WEEKLY_PLAN,
    P.VIEW_FOLLOWUP_REMINDERS,
    P.VIEW_CUSTOMER_PROFILE,
    P.VIEW_ALL_KAM_DASHBOARDS,
  ],
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
});

export const hasPermission = (role, permission) =>
  Array.isArray(ROLE_PERMISSIONS[role]) && ROLE_PERMISSIONS[role].includes(permission);

export const hasAnyPermission = (role, permissions = []) =>
  permissions.some((p) => hasPermission(role, p));