// src/Components/constants/permissions.js
import { ROLES } from './roles';

export const PERMISSIONS = Object.freeze({
  CREATE_RECOMMENDATION: 'CREATE_RECOMMENDATION',
  REVISE_RECOMMENDATION: 'REVISE_RECOMMENDATION',
  REQUEST_INFO_UPDATE: 'REQUEST_INFO_UPDATE',
  APPROVE_INFO_UPDATE: 'APPROVE_INFO_UPDATE',
  APPROVE_RATE: 'APPROVE_RATE',
  REJECT_RATE: 'REJECT_RATE',
  MANAGE_PROVISIONAL_ACCOUNT: 'MANAGE_PROVISIONAL_ACCOUNT',
  DRAFT_OFFER: 'DRAFT_OFFER',
  FINALIZE_OFFER: 'FINALIZE_OFFER',
  DRAFT_AGREEMENT: 'DRAFT_AGREEMENT',
  FINALIZE_AGREEMENT: 'FINALIZE_AGREEMENT',
  UPLOAD_SIGNED_AGREEMENT: 'UPLOAD_SIGNED_AGREEMENT',
  ACTIVATE_PROFILE: 'ACTIVATE_PROFILE',
  VIEW_CUSTOMER_PROFILE: 'VIEW_CUSTOMER_PROFILE',
  MANAGE_USERS: 'MANAGE_USERS',
  FULL_SYSTEM_CONTROL: 'FULL_SYSTEM_CONTROL',
});

const {
  CREATE_RECOMMENDATION, REVISE_RECOMMENDATION, REQUEST_INFO_UPDATE,
  APPROVE_INFO_UPDATE, APPROVE_RATE, REJECT_RATE, MANAGE_PROVISIONAL_ACCOUNT,
  DRAFT_OFFER, FINALIZE_OFFER, DRAFT_AGREEMENT, FINALIZE_AGREEMENT,
  UPLOAD_SIGNED_AGREEMENT, ACTIVATE_PROFILE, VIEW_CUSTOMER_PROFILE,
  MANAGE_USERS, FULL_SYSTEM_CONTROL,
} = PERMISSIONS;

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    APPROVE_INFO_UPDATE, MANAGE_PROVISIONAL_ACCOUNT, VIEW_CUSTOMER_PROFILE, MANAGE_USERS,
  ],
  [ROLES.LINE_MANAGER]: [
    APPROVE_RATE, REJECT_RATE, APPROVE_INFO_UPDATE,
    MANAGE_PROVISIONAL_ACCOUNT, VIEW_CUSTOMER_PROFILE,
  ],
  [ROLES.SALES_COORDINATOR]: [
    DRAFT_OFFER, FINALIZE_OFFER, DRAFT_AGREEMENT, FINALIZE_AGREEMENT, VIEW_CUSTOMER_PROFILE,
  ],
  [ROLES.KAM]: [
    CREATE_RECOMMENDATION, REVISE_RECOMMENDATION, REQUEST_INFO_UPDATE,
    UPLOAD_SIGNED_AGREEMENT, ACTIVATE_PROFILE, VIEW_CUSTOMER_PROFILE,
  ],
  [ROLES.OPERATIONS]: [VIEW_CUSTOMER_PROFILE],
  [ROLES.ACCOUNTS]: [VIEW_CUSTOMER_PROFILE],
});

export const hasPermission = (role, permission) =>
  Array.isArray(ROLE_PERMISSIONS[role]) && ROLE_PERMISSIONS[role].includes(permission);

export const hasAnyPermission = (role, permissions = []) =>
  permissions.some((p) => hasPermission(role, p));