// src/Pages/modules/sales/constants/salesStatus.js
export const STATUS = Object.freeze({
  PENDING_RATE: 'PENDING RATE PREPARATION',
  PENDING_APPROVAL: 'PENDING RATE APPROVAL',
  APPROVED_PENDING_OFFER: 'RATE APPROVED (GENERATE OFFER)',
  OFFER_DRAFTING: 'DRAFTING OFFER LETTER',
  OFFER_REVIEW: 'OFFER SENT (AWAITING CLIENT FEEDBACK)',
  OFFER_REJECTED: 'OFFER REJECTED (REVISE RATE)',
  PENDING_AGREEMENT: 'OFFER ACCEPTED (GENERATE AGREEMENT)',
  AGREEMENT_DRAFTING: 'DRAFTING AGREEMENT',
  AGREEMENT_REVIEW: 'AGREEMENT SENT (AWAITING SIGNATURE)',
  PENDING_PROFILE: 'AGREEMENT SIGNED (PENDING PROFILE)',
  PROVISIONAL_ACTIVE: 'PROVISIONAL ACCOUNT (ACTIVE)',
  PROVISIONAL_EXPIRED: 'PROVISIONAL ACCOUNT (EXPIRED)',
  INFO_UPDATE_PENDING: 'INFO UPDATE PENDING LM APPROVAL',
  ACTIVE: 'ACTIVE ACCOUNT',
});

export const TERMINAL_STATUSES = Object.freeze([STATUS.ACTIVE, STATUS.PROVISIONAL_EXPIRED]);

export const isPipelineStatus = (status) => !TERMINAL_STATUSES.includes(status) || status === STATUS.PROVISIONAL_ACTIVE;

export const STATUS_STYLE = Object.freeze({
  danger: [STATUS.OFFER_REJECTED, STATUS.PROVISIONAL_EXPIRED],
  success: [STATUS.ACTIVE, STATUS.PROVISIONAL_ACTIVE],
});

export const getStatusTone = (status) => {
  if (STATUS_STYLE.danger.includes(status)) return 'danger';
  if (STATUS_STYLE.success.includes(status)) return 'success';
  return 'pending';
};

export const PROVISIONAL_RULES = Object.freeze({
  VALIDITY_DAYS: 21,
  LM_EXTENSION_DAYS: 5,
});

export const CREDIT_RULES = Object.freeze({
  DEFAULT_PERIOD_DAYS: 15,
  MAX_EXTENDED_PERIOD_DAYS: 19,
});